name: ✨ 功能请求 / Feature Request
description: 建议一个新功能或改进 / Suggest a new feature or improvement
assignees:
  - XinLi-cyber
labels: 
  - "type: feature"
  - "status: waiting-for-internal-feedback"
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您的功能建议！/ Thank you for your feature suggestion!
        
        请详细描述您的想法，这将帮助我们更好地理解和评估您的建议。
        Please describe your idea in detail to help us better understand and evaluate your suggestion.
        
  - type: input
    id: summary
    attributes:
      label: 功能摘要 / Feature Summary
      description: |
        用一句话描述您想要的功能
        Describe the feature you want in one sentence
      placeholder: |
        例如：添加暗色主题支持
        Example: Add dark theme support
    validations:
      required: true
      
  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型 / Feature Type
      description: |
        这是什么类型的功能请求？
        What type of feature request is this?
      options:
        - 全新功能 / New Feature
        - 用户体验改进 / UX Improvement  
        - 性能优化 / Performance Optimization
        - "API改进 / API Enhancement"
        - 文档改进 / Documentation Improvement
        - 安全性增强 / Security Enhancement
        - 移动端支持 / Mobile Support
        - "国际化支持 / i18n Support"
        - 其他 / Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: 优先级 / Priority
      description: |
        您认为这个功能的重要程度如何？
        How important do you think this feature is?
      options:
        - 高 - 非常需要这个功能 / High - Really need this feature
        - 中 - 有了更好 / Medium - Would be nice to have
        - 低 - 可有可无 / Low - Optional
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: 问题描述 / Problem Description
      description: |
        这个功能要解决什么问题？为什么需要这个功能？
        What problem does this feature solve? Why is this feature needed?
      placeholder: |
        我遇到的问题是... / The problem I encountered is...
        
        例如 / Example:
        - 当前没有暗色主题，长时间使用眼睛疲劳
        - Currently there's no dark theme, eyes get tired after long usage
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案 / Proposed Solution
      description: |
        您希望如何解决这个问题？详细描述您设想的功能。
        How would you like to solve this problem? Describe the feature you envision in detail.
      placeholder: |
        我认为可以通过...来解决 / I think this can be solved by...
        
        例如 / Example:
        - 在设置页面添加主题切换选项，支持亮色/暗色/自动模式
        - Add theme toggle option in settings, supporting light/dark/auto modes
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Alternative Solutions
      description: |
        您考虑过其他解决方案吗？
        Have you considered any alternative solutions?
      placeholder: |
        我也考虑过... / I also considered...
        
        例如 / Example:
        - 使用浏览器扩展来改变页面样式
        - Using browser extension to change page styling
        
  - type: checkboxes
    id: confirmations
    attributes:
      label: 确认事项 / Confirmations
      description: |
        提交前请确认以下事项
        Please confirm the following before submitting
      options:
        - label: |
            我已经搜索了现有的 issues 和讨论，确认这不是重复建议
            I have searched existing issues and discussions, confirming this is not a duplicate suggestion
          required: true
        - label: |
            这个功能符合项目的目标和范围
            This feature aligns with the project's goals and scope
          required: true
        - label: |
            我理解这个功能可能需要时间来实现
            I understand this feature may take time to implement
          required: true
        - label: |
            我愿意协助实现这个功能 (可选)
            I'm willing to help implement this feature (optional)
          required: false
